// <auto-generated />
using Auftragsverwaltung;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auftragsverwaltung.Migrations
{
    [DbContext(typeof(AuftragsverwaltungDbContext))]
    [Migration("20240129193144_BasicFields3")]
    partial class BasicFields3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Auftragsverwaltung.Artikel", b =>
                {
                    b.Property<int>("ArtikelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtikelID"));

                    b.Property<int>("Artikelgruppe")
                        .HasColumnType("int");

                    b.Property<string>("Artikelname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Artikelnummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtikelID");

                    b.ToTable("Artikel");
                });
#pragma warning restore 612, 618
        }
    }
}
